In [4]:
# without search index
import openai
YANDEX_CLOUD_FOLDER = "***"
YANDEX_CLOUD_API_KEY = "***"
# YANDEX_CLOUD_MODEL = "gpt-oss-20b/latest"

Привет! Я в порядке, спасибо. А ты как? Чем занимаешься сегодня?

In [67]:
def form_prompt(review):
    return f'''
        Тебе необходимо выделить в данном ревью данные для анализа. Вот шаблон, по которому тебе необходимо отвечать:
        {json_format}, строго соответствуй этому формату
        Вот отзыв который тебе необходимо обработать: {review}
    '''
json_format = '''
{
    sentiment: positive | negative, # : Отзыв является негативным или позитивным
    reason_n: Обслуживание персонала | Качество еды | Цены | Ассортимент | Качество доставки | Чистота и атмосфера в заведении | None | Список причин [reason1, reason2, ...] # : По какой причине не понравилась пиццерия, ИСПОЛЬЗУЙ ТОЛЬКО ЭТИ КАТЕГОРИИ
    reason_p: Обслуживание персонала | Качество еды | Цены | Ассортимент | Качество доставки | Чистота и атмосфера в заведении | None | Список причин [reason1, reason2, ...] # : По какой причине понравилась пиццерия, ИСПОЛЬЗУЙ ТОЛЬКО ЭТИ КАТЕГОРИИ
}
'''

In [14]:
response = client.responses.create(
    model=f"gpt://{YANDEX_CLOUD_FOLDER}/{YANDEX_CLOUD_MODEL}",
    temperature=0.1,
    instructions="You are special model, designed to help to analyze the reviews of pizzerias. Answer only in json format",
    input=form_prompt(list(df.text)[0]),
    max_output_tokens=300
)

print(response.output_text)

{
  "sentiment": "positive",
  "reason_n": "None",
  "reason_p": ["Качество еды", "Качество доставки", "Обслуживание персонала"]
}

In [8]:
import pandas as pd
df = pd.read_csv('pj.csv', delimiter=';')

In [34]:
pd.DataFrame(result).to_csv('PJ_review_analyzed.csv')

In [37]:
df = pd.DataFrame(result)
df[df.sentiment == 'negative']

,company,sentiment,reason_n,reason_p,review_text
9,Папа Джонс,negative,"[Качество доставки, Обслуживание персонала]",None,"Опоздали с доставкой, но это ладно не беда, бе..."
12,Папа Джонс,negative,"[Качество доставки, Цены]",None,"Ужасное заведение. Сделал заказ по телефону, а..."
39,Папа Джонс,negative,"[Качество доставки, Обслуживание персонала]",None,Заказ в статусе «Готовится» уже больше часа. Т...
41,Папа Джонс,negative,"[Качество еды, Качество доставки]",None,"Полный негатив, пицца не вкусная, ужасное каче..."
42,Папа Джонс,negative,[Качество еды],"[Качество еды, Обслуживание персонала]","Сильно испортилось качество пиццы, один майоне..."
...,...,...,...,...,...
1299,Папа Джонс,negative,"[Цены, Качество еды]",None,"Кофе по факту 0,2, а не 0,3 за 220 рублей. Ужа..."
1326,Папа Джонс,negative,[Обслуживание персонала],[None],Я с области приехала в Москву в эту Додо Пиццу...
1334,Папа Джонс,negative,"[Проблемы с приложением, Качество еды (один ра...","[Чистота и атмосфера в заведении, Качество еды]","Была любимая пиццерия: просторная, готовят вку..."
1343,Папа Джонс,negative,[Обслуживание персонала],None,"Ужасно провели инвент с zzz, билеты были все к..."
1345,Папа Джонс,negative,[Обслуживание персонала],None,Здравствуйте! Хотелось бы уточнить на счет иве...

In [11]:
list(df.text)[0]

'Сегодня заказывал пиццу, закуски, напитки, десерты с доставкой ко времени. Всё вовремя, вопросов нет. Пицца — вкусно, заказывал на тонких коржах. Молодцы. Доставщик вежливый, помог поднять на этаж. Я в заказе не указал, что до двери. Забыл. Всё упаковано отлично. На…'

In [7]:
data = ''
with open('pj.csv', 'r') as f:
    data = f.read()
data

'company;company_id;author;date;rating;text\nПапа Джонс;204403165844;Сергей Сергей;2025-10-13T11:05:25.156Z;5;Сегодня заказывал пиццу, закуски, напитки, десерты с доставкой ко времени. Всё вовремя, вопросов нет. Пицца — вкусно, заказывал на тонких коржах. Молодцы. Доставщик вежливый, помог поднять на этаж. Я в заказе не указал, что до двери. Забыл. Всё упаковано отлично. На…\nПапа Джонс;204403165844;Надежда Вовченко;2025-10-02T19:07:25.116Z;5;Очень хорошее заведение,постоянно здесь заказываю.Очень нравятся пицца Альфредо,Мясная,Томатная с Креветками,в меню также есть Вегетарианская пицца.Вкусный картофель с курицей и опятами,хорошие куриные наггетсы,сырные палочки.Из напитков больше всего нравится Evervess Cola Ванильное Мороженое\nПапа Джонс;204403165844;Кристина Гущина;2025-10-22T09:38:19.016Z;5;Удобгое приложение, удобный заказ, п то что пицца тут вкусная всегда - я не сомневалась. Доставка четко ко времени, курьер заранее позвонил, как я просила. Четко все. Благодарю! Не теряйте качество и сервис\nПапа Джонс;204403165844;Илона Ч.;2025-11-07T23:19:20.805Z;5;Заказывали 07.11 пиццу на день рождения коллеги! Привезли точно к назначенному времени. Доставил пиццу невероятно вежливый и улыбчивый курьер Абдумалик, не остался в стороне и тоже передал поздравления моей…\nПапа Джонс;204403165844;Егор Тищенко;2025-09-15T18:17:10.042Z;5;Заказывали пиццу на обед, курьер примчался просто нереально быстро! Пицца была еще горячей, прямо из печи. Сам курьер был очень вежливым и аккуратным. Большое спасибо за скорость и качество! Теперь только к вам!\nПапа Джонс;204403165844;Игорь Р.;2025-10-08T08:35:14.991Z;5;Быстро приготовили и доставили! Вкусно и резонный прайс! Приятные и вежливые курьеры!\nПапа Джонс;204403165844;Ширван И.;2025-09-29T13:08:46.470Z;5;Очень вкусная пицца , буду сюда часто заезжать и заказывать доставку .Ассортимент пицц очень разнообразное , буду пробовать, ребята быстро отдали !!!\nПапа Джонс;204403165844;Полина Погосян;2025-10-10T06:59:44.305Z;5;Заказываю тут часто, всегда всё супер. Пицца приезжает горячая, курьеры вежливые, ждать долго не приходится. Приятно, когда сервис держит уровень\nПапа Джонс;204403165844;Якуб Шахвердиев;2025-07-30T14:40:36.340Z;5;Папа Джонс — номер один! Пицца всегда свежая и вкусная. Курьер Алтын доставил быстро и с улыбкой. Спасибо за отличный сервис!\nПапа Джонс;204403165844;Эрл В.;2025-06-13T14:47:21.381Z;1;Опоздали с доставкой, но это ладно не беда, беда в том что приехал курьер и пол часа делал голову мол не работает терминал оплаты, хотя я специально поставил способ оплаты картой курьеру так ккк переводом или наличкой нет возможности, стоял пол часа говорил что не работает…\nПапа Джонс;204403165844;patrashovoleg;2025-09-25T16:18:54.877Z;5;хорошая пиццерия, вкусная пицца, быстро доставляют заказы) особенно курьер Абдумалик быстро доставляет заказы💪💪💪\nПапа Джонс;204403165844;Илья Репин;2025-07-30T14:55:35.223Z;5;Отличная и вкусная пицца, доставляют как всегда вовремя, Алтын очень приятный молодой человек и хороший собеседник, всем рекомендую 🔥\nПапа Джонс;204403165844;Сергей Ш.;2025-09-05T16:49:31.955Z;1;Ужасное заведение. Сделал заказ по телефону, акцентировал внимание, что нужно привезти заказ именно к назначенному времени. В итоге курьер опоздал на полчаса, и в чек включили 5 лишних пицц, которые я не заказывал. Испорченное настроение обеспечено, не советую.\nПапа Джонс;204403165844;Дима Добровольский;2024-08-26T15:08:34.162Z;5;Шикарный курьер, отдельное спасибо за оперативность и горячию пиццу. Люблю и буду заказывать еще, лутшая пицца на Арбате. Прекрасное отношение к определеному курьеру. Стараюсь заказывать только через Алтына. Всегда четко)\nПапа Джонс;204403165844;Тетерин Егор;2025-04-11T12:52:13.979Z;5;Не один раз заказывал здесь пиццу, всегда привозили достаточно быстро и почти горячую, сама пиццы вкусная, да и ассортимент большой, всем кто рядом живет однозначно рекомендую.\nПапа Джонс;204403165844;Сергей Васильев;2024-06-24T07:32:22.078Z;5;Papa John\'s - отличное место для любителей пиццы! Заказывал несколько раз, и каждый раз пицца была вкусной и свежей. Доставка всегда вовремя, курьеры вежливые. Рекомендую!\nПапа Джонс;204403165844;Kamila Mairko;2024-12-09T16:55:07.661Z;5;Попался очень вежливый курьер! Очень быстрая доставка, привезли горячую пиццу. В общем рекомендую вам данное заведение, сотрудники молодцы, выполняют свою работу на отлично)\nПапа Джонс;204403165844;Анастасия Василевская;2025-10-10T06:04:04.703Z;5;"Очень вкусно! Пицца просто огонь, тесто тонкое, ингредиенты свежие. Рекомендую!\nКурьер Абдумалик привез всё очень быстро."\nПапа Джонс;204403165844;Алексей Рожников;2024-11-08T15:37:37.130Z;5;Крутое место, прекрасная планировка посадки, вкусная еда, отзывчивые официанты, хороший сервис, приятные цены, восхитительные напитки, тихие посетители, вайбовая атмосфера заведения\nПапа Джонс;204403165844;Артем П.;2025-03-30T20:33:29.382Z;5;Прекрасный, отзывчивый персонал, обслуживание на уровне ресторана! Пицца очень вкусная, порадовала пепперони и гавайская, все очень круто, ещё обязательно вернёмся!!!\nПапа Джонс;204403165844;Евгений Деев;2025-10-24T15:02:53.538Z;5;Отличная пиццерия, заказывали пиццули на тверскую 8, корп.2, привезли очень быстро, вежливый и оперативный курьер ! 😋\nПапа Джонс;204403165844;марта м.;2024-10-31T12:39:50.092Z;5;отличная пицца, много выбора, вежливый персонал, очень хорошая идея с наполнением для корочки, можно и с сыром и с сосиской, нам с друзьями очень понравилось, однозначно 5 звезд\nПапа Джонс;204403165844;Виктор Самохин;2025-11-05T16:03:53.979Z;5;Все отлично, быстрая доставка и вкусная пицца. Курьер Абдумалик все доставил быстро и раньше срока\nПапа Джонс;204403165844;Артур сехлян;2024-09-22T16:16:35.014Z;5;Пицца была очень вкусная, заведение персонал был вежливый все чисто уютно хорошее место чтобы отдохнуть семьей все классно советую\nПапа Джонс;204403165844;Дмитрий;2024-11-08T15:50:37.504Z;5;Отличный ресторанчик, ставлю только 5/5 Чисто, дружелюбный персонал и прекрасная доставка. Доставили пока еще горячее и в целости. Буду заказывать только здесь!!!! Советую\nПапа Джонс;204403165844;Анастасия Анастасия;2025-11-06T14:36:12.775Z;5;Большое спасибо за вкусную пиццу! Спасибо курьеру Абдумалику, который доставил всё вовремя! Коллеги довольны!\nПапа Джонс;204403165844;Инкогнито 5210;2025-10-29T18:58:49.510Z;5;Очень быстро привезли, вовремя. Пицца очень вкусная. Курьер Абдумалик - очень хороший курьер. Спасибо!\nПапа Джонс;204403165844;Kasper14;2024-11-06T13:37:27.513Z;5;очень вкусная пицца, заказывал в этой пиццери, все привезли быстро, пицца была горячая, курьер вежливый, очень приятный сервис\nПапа Джонс;204403165844;Hovrosh;2025-10-12T09:45:16.292Z;5;Отличная пиццерия, все доставляют своевременно! Курьер Абдумалик очень быстро все доставил\nПапа Джонс;204403165844;Дарья Р.;2024-10-22T12:08:49.724Z;5;Прекрасная пицца, очень вкусно! Доставка пришла вовремя, курьер очень вежливый и доброжелательный. Будем заказывать еще!\nПапа Джонс;204403165844;Миладка Плетнёва;2025-10-11T17:26:22.474Z;5;Спасибо за быструю доставку! Вкусная, свежая пицца) Курьер Абдумалик максимально учтив и заботлив👍\nПапа Джонс;204403165844;Александра;2025-10-23T07:57:46.239Z;5;"очень вкусная пицца и курьер безмерно приятный!! \nбыстро приняли и привезли заказ"\nПапа Джонс;204403165844;sashakiseleva09@icloud.com;2025-10-27T11:43:57.619Z;5;Лучшее заведение , всегда из него заказываю , всегда приезжает вкусная горячая пицца , всем рекомендую\nПапа Джонс;204403165844;Лаюса;2025-11-07T10:48:52.876Z;5;Заказывали пиццу. Очень быстрая доставка, вкусная пицца. Спасибо курьеру и работникам кухни🤗\nПапа Джонс;204403165844;Хеда Ермалаева;2025-10-14T12:14:59.442Z;5;Очень вкусная пицца ,приветливый персонал . Удобная локация. Есть место для парковки .\nПапа Джонс;204403165844;мирзорахим мирзорахимов;2025-09-23T04:15:03.303Z;5;Хороший пецца очень вкусный рекомендую всём спасибо курьер очень вежливый персонал быстро доставили спасибо рекомендую всем сотрудникам всем приятного аппетита\nПапа Джонс;204403165844;Георгий Мамедов;2024-12-19T17:29:34.170Z;5;"Отличная место,очень вкусная,персонал очень быстрый добрый и внимательный \nвсем советую ,закажу не один раз"\nПапа Джонс;204403165844;Alina Chekirlan;2024-12-19T18:22:32.414Z;5;Классная пиццерия, очень понравился ассортимент, много выбора. Дружелюбный персонал и демократичные цены 🤩\nПапа Джонс;204403165844;Костя;2025-09-23T22:45:15.155Z;5;Забирал здесь пиццу 23 сентября. Через окно выдачи увидел чистую кухню. А приветливая сотрудница Лиля отдала заказ своевременно.\nПапа Джонс;204403165844;Анастасия Смурова;2025-02-16T17:11:38.290Z;1;Заказ в статусе «Готовится» уже больше часа. Телефон ресторана не отвечает. В поддержке отбивки от бота. Отменить заказ и вернуть деньги не получается. Испорченное настроение и ужин. Сервис на единицу. Не рекомендую заказывать.\nПапа Джонс;204403165844;Дарья Седова;2025-10-22T07:06:03.159Z;5;Хорошая пицца!!! Очень вкусно. Курьер- Абдумалик, быстро доставляет и всегда с прекрасным настроением!\nПапа Джонс;204403165844;Андрей Кондрашов;2025-01-03T20:45:33.679Z;1;Полный негатив, пицца не вкусная, ужасное качество, как будто не папа Джонс, а забегаловка. Курьер неквалифицированный, пицца ледяная, перевернутая. Курьера зовут Ильяс, заказывал недалеко, близко к метро.\nПапа Джонс;204403165844;Дарья Ч.;2023-11-21T07:48:35.543Z;1;Сильно испортилось качество пиццы, один майонез и кетчуп в составе. Пицца сырная, ветчина и сыр и Маргарита - ужасные на вкус. вместо сыра один майонез. Раньше заказывала в офис на др, всё нравилось, в этом году разница ощутима. Коллеги в этот раз не съели и половины из того,…\nПапа Джонс;204403165844;КАМОЛ УБАЙДУЛЛАЕВ;2025-10-04T18:23:23.084Z;5;Очень вкусно спасибо курьер очень вежливый Абдумалик быстро приехал спасибо большое\nПапа Джонс;204403165844;Наталья Г.;2025-11-01T12:26:48.193Z;5;Очень нравится, вкусно, быстрая доставка, курьеры приятные и вежливые. Заказываем давно. Спасибо!\nПапа Джонс;204403165844;Екатерина Вейдеман;2025-10-11T11:29:08.477Z;5;Абдумалек быстро доставил. Спасибо большое! Пицца очень вкусная! Спасибо всем большое\nПапа Джонс;204403165844;Глеб Е.;2024-12-19T19:20:00.644Z;5;"Вкусная пицца, команда номер один! Очень рекомендую это место для вечерних посиделок. \nПрекрасный работник Алтын."\nПапа Джонс;204403165844;Сергей Сафонов;2024-06-22T16:05:41.110Z;5;Папа Джонс - всегда радует! Заказываю пиццу здесь часто, и каждый раз остаюсь доволен. Всегда свежие ингредиенты и отличный вкус. Рекомендую!\nПапа Джонс;204403165844;Андрей Шаров;2024-08-26T15:07:49.612Z;5;Очень все быстро, и вкусная пицца я был поражен как тому что все как на сайте так и в живую, картинка полностью передает свой вкус\nПапа Джонс;204403165844;Михаил Стеценко;2024-02-18T18:33:18.161Z;1;Привезли просто развалившуюся и холодную пиццу … Просто у курьера в руках пицца и отдельно пакет с морсом и чеком , даже не удосужились положить пару салфеток . Мы приехали в гости на 2 дня , хотели поужинать в отеле . Увы, но мы не смогли проглотить «это»…\nПапа Джонс;204403165844;Инкогнито 6970;2025-09-25T09:13:13.006Z;5;Заказала большой заказ в офис, все пришло во время. Курьер был всегда на связи, отдельное ему спасибо!\nПапа Джонс;204403165844;Давид Мануков;2024-11-08T15:42:24.019Z;5;Хорошая вкусная пицца, готовят быстро. Всем рекомендую четыре сыра у них.\nПапа Джонс;204403165844;Ваня Пенязев;2024-12-09T15:26:25.583Z;5;Я решил заказать пиццу и не пожалел,привезли быстро и очень вкусно.заказывайте только папа Джонс\nПапа Джонс;204403165844;Иван Иванов;2024-11-01T12:05:03.676Z;5;Отличное место, всегда вкусно и вовремя. А доставка радует ещё больше думаю одна из самых быстрых в Москве!!!!\nПапа Джонс;204403165844;Тимофей;2025-05-05T11:44:10.964Z;5;Хорошее место, часто берём на вынос. Готовят быстро, к качеству не разу не было претензий.\nПапа Джонс;204403165844;Валерия;2025-10-06T19:02:42.781Z;5;Очень вкусная пицца! Отличное заведение для хорошего вечера с семьей 💗 спасибо!\nПапа Джонс;204403165844;Софья Кузьминова;2025-09-30T19:40:48.126Z;5;Очень нравится это заведение, еда вкусная, атмосфера спокойная и комфортная, приду еще раз\nПапа Джонс;204403165844;Александр Игоревич;2024-04-06T11:36:00.962Z;5;Papa John\'s - отличный выбор для любителей пиццы! Я несколько раз заказывал у них пиццу, и каждый раз был приятно удивлен качеством и вкусом. Ингредиенты всегда свежие, а их разнообразие позволяет выбрать пиццу по своему вкусу.\nПапа Джонс;204403165844;София С.;2025-10-11T17:11:22.645Z;5;Вкусная и хорошая пицца, курьер Абдулмалик быстро доставал заказ !\nПапа Джонс;204403165844;Иван Разкразомхозов;2025-01-31T12:11:29.710Z;5;Вкуснейшая пицца, привезли вовремя, все вкусно и качественно, курьер очень добрый!\nПапа Джонс;204403165844;Алина сафонова;2025-10-02T15:45:01.390Z;5;Очень вкусная пицца, курьер Абдумалик быстро доставляет заказы\nПапа Джонс;204403165844;дарья ретюнских;2025-10-10T18:55:39.323Z;5;Очень вкусная пицца, курьер Абдумалик очень быстро доставил 👍\nПапа Джонс;204403165844;Моисей Погосян;2025-10-07T17:24:58.460Z;5;Очень вкусная пицца, заказывали на компанию, спасибо супер аккуратному и оперативному курьеру Абдумалику, очень добродушный сотрудник!…\nПапа Джонс;204403165844;Кирилл Горюнов;2025-07-30T13:48:23.306Z;5;Вкусная пицца, хороший персонал, чистое помещение\nПапа Джонс;204403165844;Егор Сыресин;2025-07-30T13:51:26.521Z;5;хорошее заведение,приятное место и быстро приготовили мою пепперони\nПапа Джонс;204403165844;Марина А.;2025-10-04T12:32:40.463Z;5;Отличная пицца! Всегда заказываю. Курьер Абдумалик быстро доставляет!\nПапа Джонс;204403165844;Максим;2024-12-19T19:15:14.853Z;5;Отличная пиццерия! Команда замечательная, пицца вкусная, чисто, уютно!)\nПапа Джонс;204403165844;Вадим Павлов;2025-09-18T22:20:28.692Z;5;Хорошая пицца как всегда, курьер доставил быстро, часто захожу.\nПапа Джонс;204403165844;Эмиль Нуриев;2025-07-30T13:50:39.678Z;5;Спасибо персоналу за свою работу . Очень уютно и вкусно . Придем обязательно еще\nПапа Джонс;204403165844;Инкогнито 4303;2024-08-25T17:43:06.775Z;5;Очень вкусная пицца, посоветую всем, что вот эту пиццу пользуется народ тоже хороший людей, тоже хороший быстрые доставки, и всё такое.\nПапа Джонс;204403165844;Александр;2024-11-21T15:17:36.090Z;5;Очень вкусная пицца, и доставить успели к офису по времени (тёплая) коллектив съел и на ура!\nПапа Джонс;204403165844;Исоян Левон;2024-09-22T16:23:40.367Z;5;Заведение очень хорошее ! Кормят вкусно 😋 Приятно проводить время в кругу друзей, кушая лучшую пиццу на патриарших прудах\nПапа Джонс;204403165844;Екатерина;2025-09-29T13:33:35.768Z;5;"Очень вкусная пицца \nВсегда все быстро и качественно👍"\nПапа Джонс;204403165844;Георгий;2025-05-09T14:30:05.473Z;5;Хороший сервис, вкусная пицца, место уютное и кайфовая, обслуживание хорошое\nПапа Джонс;204403165844;Бактыбек Манапов;2025-09-23T17:53:54.571Z;5;"Пицца вкусная и быстро доставляет \nКурьер супер просто"\nПапа Джонс;204403165844;Кирилл Неважно;2024-11-02T15:20:08.332Z;5;Всем советую попробовать эту пиццу! Она была очень вкусной и доставили её вовремя.\nПапа Джонс;204403165844;Максим Табаран;2025-10-02T13:51:41.071Z;5;"Очень вкусная пицца\nКурьер Абдумалик быстро доставил заказ\nМолодец"\nПапа Джонс;204403165844;Андрей Трунькин;2025-11-06T10:41:10.420Z;5;Отличная доставка, привезли очень быстро. Курьер Абдамалик очень заботливый)\nПапа Джонс;204403165844;Илёсбек Самадов;2024-09-14T19:32:54.294Z;5;Заказали тут пиццу очень вкусная и ещё они на пиццу добавляют халапено это очень приятно и вкусно 🤤\nПапа Джонс;204403165844;Артём;2024-09-30T12:31:18.763Z;5;Очень приятное место, очень отзывчивый персонал, и очень вкусная пицца\nПапа Джонс;204403165844;Евгений И.;2024-12-22T09:14:16.022Z;5;Отличная пиццерия! Все нравится, скорость обслуживания и вежливость сотрудников!\nПапа Джонс;204403165844;Mikhail Loginov;2024-04-27T16:51:41.477Z;1;"Самая ужасная пицца которую я ел в папе\nДжонс. Заказывал у вас пиццу несколько раз, всегда была очень вкусная пицца. В этот раз я был ошеломлен качеством. Борты как половина пиццы,хотя, я заказывал пиццу с тонким тестом, сыр ужасного качества,…"\nПапа Джонс;204403165844;Александр Г.;2025-09-22T09:27:54.224Z;5;Быстрая доставка, приятный курьер, а самое главное вкусно\nПапа Джонс;204403165844;Кирилл .;2024-10-31T12:34:18.377Z;5;Вкусная, качественная, горячая пицца. Отличное обслуживание, привезли сразу.\nПапа Джонс;204403165844;Вероника К.;2024-11-05T17:41:11.434Z;5;Очень вкусная пицца, доставка быстрая, пицца горячая, советую!\nПапа Джонс;204403165844;Ваге Зурабян;2024-12-19T18:30:18.845Z;5;Горячая и вкусная пицца, доставка быстрая, всё очень понравилось\nПапа Джонс;204403165844;Саша Виноградова;2025-10-29T12:55:13.106Z;5;Очень вкусная горячая пицца, все быстро, всегда покупаю здесь! Советую!\nПапа Джонс;204403165844;Роберт Б.;2025-03-27T12:33:29.542Z;5;"Доставщики лучшие \nОчень вкусная пицца и особенно доставщик Алтын"\nПапа Джонс;204403165844;Дмитрий Дмитрий;2025-10-12T10:39:48.447Z;5;Частенько заказываю пиццу, быстро готовят и очень вкусно.\nПапа Джонс;204403165844;yaroslavsolov1964;2025-09-21T15:26:46.474Z;5;Хорошая пицца, курьеры молодцы быстро доставляют\nПапа Джонс;204403165844;Раван Н.;2025-07-30T14:42:49.744Z;5;"Хорошая птицца хорошее обслуживание 🤝🏻\nДоставщик алтын очень хороший и добрый"\nПапа Джонс;204403165844;Ирина;2022-04-19T07:16:33.931Z;5;Очень вкусное и пышное тесто и сочная пицца. Обожаю папа джонс, это настоящая пицца а не не то, что на других местах тонкое тесто как лаваш и томат. Огромная благодарность компанию особенно сотрудникам на молчановке. Сколько раз заказываем как всегда все вкусно. Раньше…\nПапа Джонс;204403165844;Василий Кавка;2025-10-05T06:56:57.568Z;5;Курьер Абдумалик быстро доставляет. Очень вкусная пицца\nПапа Джонс;204403165844;Юлия П;2021-03-19T16:49:12.917Z;5;Вчера заказали пиццу в «Папа Джонс». Привезли быстро, всё было тёплое и вкусное. Курьер очень вежливый и интеллигентный. Курьер забыл передать заказанный мусс в бутылочке, но вскоре вернулся, и привёз наряду с муссом ещё одну пиццу в подарок , совершено бесплатно, очень вкусную и тёплую. Большое спасибо за отличный сервис и вкусную еду!\nПапа Джонс;204403165844;Ольга Анастасиади;2024-12-02T13:09:35.119Z;5;Все очень круто, пицца отменная а самое главное это прекрасное место чтобы поесть с дрзуьяии!\nПапа Джонс;204403165844;Тимур Черняков;2025-01-07T13:39:13.124Z;5;Отличное заведение для перекуса, вкусная пицца и хорошее обслуживание прилагаются.\nПапа Джонс;204403165844;Илхом Рузикулов;2025-10-05T13:23:22.109Z;5;Хороший пицца , очень вкусно. Курир Абдумалик быстро доставлял. Моладис он\nПапа Джонс;204403165844;Иван Павлов;2025-10-05T10:09:05.322Z;5;Отлично быстро привезли, курьер Абдумалик горячая и вкусная!\nПапа Джонс;204403165844;....;2025-03-30T19:25:08.988Z;5;"великолепное место очень вкусная пицца\nвежливый персонал"\nПапа Джонс;204403165844;Людмила К.;2023-04-02T14:28:09.979Z;5;заказала пиццу Супер Папа и Мясную пиццу заказываю не первый раз потому что здесь она очень вкусная и готовят ее быстро персонал приветливый и внимательный процветания им!!!\nПапа Джонс;204403165844;faithgod;2024-11-02T18:18:56.634Z;5;Отличная пицца, вкусная, курьер доставил во время, была горячая\nПапа Джонс;204403165844;.;2025-03-30T19:24:43.943Z;5;Прекрасное место, вежливый персонал, вкусная еда. Однозначно рекомендую, придем сюда ещё!\nПапа Джонс;204403165844;Александр Корвус;2025-02-02T19:22:19.139Z;5;Очень хорошее обслуживание, возят горячую пиццу, смак. очень вкусно)\nПапа Джонс;204403165844;Дмитрий Лыков;2024-12-16T19:28:09.273Z;5;Шикарное место, обслуживание на высшем уровне: официанты были внимательными и отзывчивыми, всегда готовы помочь с выбором.\nПапа Джонс;204403165844;Максим Е.;2024-08-17T16:28:24.537Z;5;Всё быстро привезли, пицца горячая и очень вкусная, всё вовремя, всё круто!\nПапа Джонс;204403165844;Елизавета Шор;2024-10-31T12:51:44.270Z;5;Вкусная пицца, быстрое время ожидания и вежливый персонал !!\nПапа Джонс;204403165844;Ольга Лешкевич;2025-10-17T11:24:29.883Z;5;"Доставка во время! Вежливый курьер! \nВсе понравилось, заказываем не первый

In [72]:
import pandas as pd
df = pd.read_csv('reviews_all.csv')
df

,Unnamed: 0,company_name,name,icon_href,date,text,stars,answer,company
0,0,Игорь,https://avatars.mds.yandex.net/get-yapic/40841...,1.761722e+09,Хочу поблагодарить команду Папа Джонс за отлич...,Хочу поблагодарить команду Папа Джонс за отлич...,"Ценим каждый отзыв! Рады, что вам понравилось!",NaN,Папа
1,1,Incognito 3277,https://avatars.mds.yandex.net/get-yapic/68143...,1.747658e+09,Заказала пиццу через Яндекс Еда. Привезли быст...,Заказала пиццу через Яндекс Еда. Привезли быст...,NaN,NaN,Папа
2,2,Светлана А.,https://avatars.mds.yandex.net/get-yapic/50595...,1.749633e+09,11.06.2025 мною был осуществлен заказ пиццы на...,11.06.2025 мною был осуществлен заказ пиццы на...,NaN,NaN,Папа
3,3,Bushcraft_girl,https://avatars.mds.yandex.net/get-yapic/39727...,1.749049e+09,"Самая ужасная доставка, но самая вкусная пицца...","Самая ужасная доставка, но самая вкусная пицца...",NaN,NaN,Папа
4,4,Julia T.,https://avatars.mds.yandex.net/get-yapic/50595...,1.747407e+09,Крылышки ничего. Но пицца…просто ужасная: тонк...,Крылышки ничего. Но пицца…просто ужасная: тонк...,NaN,NaN,Папа
...,...,...,...,...,...,...,...,...,...
5669,5669,Надежда.,https://avatars.mds.yandex.net/get-yapic/51169...,1.668492e+09,Вкусная пицца!,Вкусная пицца!,"Спасибо за высокую оценку, Надежда! Рады, что ...",NaN,Zotman:
5670,5670,Д,https://avatars.mds.yandex.net/get-yapic/45131...,1.652020e+09,Шикарная пицца для заказа на дом.,Шикарная пицца для заказа на дом.,NaN,NaN,Zotman:
5671,5671,Igor Zuev,https://avatars.mds.yandex.net/get-yapic/54535...,1.683219e+09,Вкусная пицца,Вкусная пицца,"Спасибо, что оценили, Игорь! Рады радовать🥰 Жд...",NaN,Zotman:
5672,5672,Глеб,https://avatars.mds.yandex.net/get-yapic/51381...,1.669482e+09,За бутерброд с Мортаделлой 😁,За бутерброд с Мортаделлой 😁,"Глеб, спасибо за высокую оценку! Приходите снова😉",NaN,Zotman:
5673,5673,Вадим,https://avatars.mds.yandex.net/get-yapic/40138...,1.684242e+09,Молодцы!!!,Молодцы!!!,Спасибо за высокую оценку!🥰 Рады стараться! Ж...,NaN,Zotman:

In [42]:
s = '''💾 Папа Джонс: сохранено 600 строк
💾 Папа Джонс: сохранено 569 строк
💾 Папа Джонс: сохранено 200 строк
💾 Папа Джонс: сохранено 337 строк
💾 Додо: сохранено 600 строк
💾 Додо: сохранено 600 строк
💾 Додо: сохранено 600 строк
💾 Додо: сохранено 0 строк
💾 Додо: сохранено 101 строк
💾 Zotman: сохранено 242 строк
💾 Zotman: сохранено 363 строк
💾 Zotman: сохранено 600 строк
💾 Zotman: сохранено 600 строк
💾 Zotman: сохранено 193 строк
💾 Zotman: сохранено 69 строк'''

In [47]:
lst = list(map(lambda line: (line.split()[1], line.split()[-2]), s.split('\n')))

In [48]:
sum(map(lambda x: int(x[1]), lst))

5674

In [51]:
company = []
for x, y in lst:
    company.extend([x] * int(y))
len(company)

5674

In [52]:
df['company'] = company
df

,company_name,name,icon_href,date,text,stars,answer,company
0,Игорь,https://avatars.mds.yandex.net/get-yapic/40841...,1.761722e+09,Хочу поблагодарить команду Папа Джонс за отлич...,5,"Ценим каждый отзыв! Рады, что вам понравилось!",NaN,Папа
1,Incognito 3277,https://avatars.mds.yandex.net/get-yapic/68143...,1.747658e+09,Заказала пиццу через Яндекс Еда. Привезли быст...,1,NaN,NaN,Папа
2,Светлана А.,https://avatars.mds.yandex.net/get-yapic/50595...,1.749633e+09,11.06.2025 мною был осуществлен заказ пиццы на...,1,NaN,NaN,Папа
3,Bushcraft_girl,https://avatars.mds.yandex.net/get-yapic/39727...,1.749049e+09,"Самая ужасная доставка, но самая вкусная пицца...",1,NaN,NaN,Папа
4,Julia T.,https://avatars.mds.yandex.net/get-yapic/50595...,1.747407e+09,Крылышки ничего. Но пицца…просто ужасная: тонк...,1,NaN,NaN,Папа
...,...,...,...,...,...,...,...,...
5669,Надежда.,https://avatars.mds.yandex.net/get-yapic/51169...,1.668492e+09,Вкусная пицца!,5,"Спасибо за высокую оценку, Надежда! Рады, что ...",NaN,Zotman:
5670,Д,https://avatars.mds.yandex.net/get-yapic/45131...,1.652020e+09,Шикарная пицца для заказа на дом.,5,NaN,NaN,Zotman:
5671,Igor Zuev,https://avatars.mds.yandex.net/get-yapic/54535...,1.683219e+09,Вкусная пицца,5,"Спасибо, что оценили, Игорь! Рады радовать🥰 Жд...",NaN,Zotman:
5672,Глеб,https://avatars.mds.yandex.net/get-yapic/51381...,1.669482e+09,За бутерброд с Мортаделлой 😁,5,"Глеб, спасибо за высокую оценку! Приходите снова😉",NaN,Zotman:
5673,Вадим,https://avatars.mds.yandex.net/get-yapic/40138...,1.684242e+09,Молодцы!!!,5,Спасибо за высокую оценку!🥰 Рады стараться! Ж...,NaN,Zotman:

In [93]:
from tqdm import trange
import openai
import ast
import json
result = []
def form_prompt(review):
    return f'''
        Тебе необходимо выделить в данном ревью данные для анализа. Вот шаблон, по которому тебе необходимо отвечать:
        {json_format}, строго соответствуй этому формату
        Вот отзыв который тебе необходимо обработать: {review}. Answer with only json object.
    '''
YANDEX_CLOUD_MODEL = "gemma-3-27b-it/latest"
json_format = '''
{
    sentiment: positive | negative, # : Отзыв является негативным или позитивным
    reason_n: Обслуживание персонала | Качество еды | Цены | Ассортимент | Качество доставки | Чистота и атмосфера в заведении | None | Список причин [reason1, reason2, ...] # : По какой причине не понравилась пиццерия, ИСПОЛЬЗУЙ ТОЛЬКО ЭТИ КАТЕГОРИИ
    reason_p: Обслуживание персонала | Качество еды | Цены | Ассортимент | Качество доставки | Чистота и атмосфера в заведении | None | Список причин [reason1, reason2, ...] # : По какой причине понравилась пиццерия, ИСПОЛЬЗУЙ ТОЛЬКО ЭТИ КАТЕГОРИИ
}
'''
YANDEX_CLOUD_FOLDER = "b1g8qv08h6hjp53m3ota"
YANDEX_CLOUD_API_KEY = "***"
client = openai.OpenAI(
    api_key=YANDEX_CLOUD_API_KEY,
    base_url="https://rest-assistant.api.cloud.yandex.net/v1",
    project=YANDEX_CLOUD_FOLDER
)
for i in trange(len(df)):
    # print(df.iloc[i]['text'])
    # print(df.iloc[i]['company'])
    response = client.responses.create(
        model=f"gpt://{YANDEX_CLOUD_FOLDER}/{YANDEX_CLOUD_MODEL}",
        temperature=0.1,
        instructions="You are special model, designed to help to analyze the reviews of pizzerias. Answer only in json format",
        input=form_prompt(df.iloc[i]['text']),
        max_output_tokens=500
    )
    try:
        obj = json.loads(response.output_text[7:-3])
        # obj = ast.literal_eval(response.output_text)
        result.append({'company': df.iloc[i]['company'], 'sentiment': obj['sentiment'], 'reason_n': obj['reason_n'], 'reason_p': obj['reason_p'],
                   'review_text': df.iloc[i]['text']})
    except Exception as e:
        print(e)
        result.append({'company': df.iloc[i]['company'],  'review_text': df.iloc[i]['text']})
        print('Response text: ' + response.output_text[7:-3])
        print('review_text:')
result

100%|██████████| 992/992 [1:08:26<00:00,  4.14s/it]

[{'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Чистота и атмосфера в заведении'],
  'review_text': 'Недавно посетил пиццерию "До До" и остался в полном восторге! Атмосфера заведения очень уютная и дружелюбная, что создает отличное настроение с самого порога. Интерьер оформлен в приятных теплых тонах, а музыка на фоне создает расслабляющую атмосферу…'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды'],
  'review_text': 'Зашли с мамой в пиццерию «До-до», заказали новинку,закуски очень сытные,горячие и максимально приятные,додстер тает во рту! Столько сыра и начинки с тонким тестом- просто сказка! Обязательно придём ещё)'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Чистота и атмосфера в заведении', 'Ассортимент'],
  'review_text': 'Приятная пиццерия, дизайн логотипа на кафешке ещё старый аутентичный с птицей Додо, которая тащит пиццу под мышкой. Милая Додошинька, во многом благодаря привлекательности бренда регулярно посещаю эти пиццерии в разных частях города и заказываю не только…'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Чистота и атмосфера в заведении',
   'Обслуживание персонала',
   'Качество еды'],
  'review_text': 'Очень нравится приходить именно сюда! Здесь на втором этаже так спокойно и уютно! Персонал очень внимательный и вежливый. Приятно, что заходишь с холодной улицы, берёшь горячую пиццу, и как дома, на диванчике, ешь неспеша!'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Обслуживание персонала', 'Качество еды', 'Цены'],
  'review_text': 'Додо пиццу очень люблю и оказавшись в Москве непременно заскочил на перекус.  Быстро готовят, персонал всегда доброжелателен, предложат Вам комбо заказы, где можно сэкономить, ну, и додо коины Вам в копилку (если пользуетесь приложением). Я рекомендую!'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды', 'Обслуживание персонала', 'Качество доставки'],
  'review_text': 'Огромное спасибо за вкуснейшую пиЦЦу и отличный сервис! Заказывали пиццу «Пепперони» и «Маргариту» - обе приехали горячими и свежими, тесто просто идеальное, тонкое и хрустящее. Особенно порадовала оперативность доставки — курьер приехал раньше указанного…'},
 {'company': 'Додо:',
  'sentiment': 'negative',
  'reason_n': ['Качество еды'],
  'reason_p': ['Качество еды'],
  'review_text': 'Пицца как всегда на отлично, а вот молочный коктейль второй раз подкачал. Перед этим разом Додо посещал в Павловском Посаде - там тоже какие-то проблемы с коктейлем - просто сладкое молоко((( брал и себе и ребенку - разных вкусов. Надеюсь качество подтянется.'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Обслуживание персонала', 'Качество еды', 'Качество доставки'],
  'review_text': 'Тоже хотел бы выразить огромную благодарность, всем сотрудникам, до до Пицца. Сегодня сделал заказ, первый раз именно в данном помещении. И всё безусловно понравилось. Сотрудники, как и везде на высоте. Всё приготовили во время. всё очень вкусно. Единственное,…'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Обслуживание персонала',
   'Качество еды',
   'Чистота и атмосфера в заведении'],
  'review_text': 'На днях впервые посетили данную пиццерию, остались крайне довольны как сервисом так и выбором продукции. Заказ делается быстро, внутри чисто и приятная атмосфера, толп и суеты нет!  Главное, что Дети получили удовольствие, а если довольны дети, то и…'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Чистота и атмосфера в заведении',
   'Обслуживание персонала',
   'Качество еды'],
  'review_text': 'место очень светлое и уютное, приветливые, добровольные сотрудники😊😊 еда тоже очень вкусная, пицца нежная и воздушная, однозначно рекомендую всем к посещению!'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Чистота и атмосфера в заведении',
   'Качество еды',
   'Качество доставки'],
  'review_text': 'Пицеррия нормис, все чисто и аккуратно. Можно посмотреть как готовится ваша пицца. Довольно быстро сделали заказ на 3 штуки. Есть второй этаж, но мы туда не заходили, и на первом круто. Сама пицца классная, не горелая и тому подобное. Наелись, у меня прошла депрессия.'},
 {'company': 'Додо:',
  'sentiment': 'negative',
  'reason_n': ['Качество доставки'],
  'reason_p': [],
  'review_text': 'Ужасно провели инвент с zzz, билеты были все куплены моментально, причём некоторые видимо покупали по 2+ билета сразу в можно лицо, потому что были люди, которые заходили по 6 раз. Додо в этот раз совсем оплошали, уж в лототроне наверняка не всем бы достался коллекционный мерч, а тем кто стоял в живой очереди вы даже не оставили шанса.'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Чистота и атмосфера в заведении',
   'Качество еды',
   'Обслуживание персонала'],
  'review_text': 'Уютно, вкусно и приветливый персонал! Большое окно, много света, приятно сидеть. Из многих додо чаще бываю в этом заведении.'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Чистота и атмосфера в заведении',
   'Обслуживание персонала',
   'Качество еды'],
  'review_text': 'Утром в ресторане спокойно и максимально уютно. Установили новые киоски самообслуживания на кассу, можно не ждать кассира и заказать быстрее, и глянуть картинки как выглядит пицца. Ребята работают шустро - а кофе и омлет утром заряжают на продуктивный день!'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Обслуживание персонала',
   'Качество еды',
   'Чистота и атмосфера в заведении'],
  'review_text': 'Очень классный сервис! Хорошая еда и классный персонал.Есть второй этаж.Приветливый персонал и отличное обслуживание.Чисто и стильно, все что нужно для идеального похода за пиццой!)'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Обслуживание персонала',
   'Качество еды',
   'Чистота и атмосфера в заведении'],
  'review_text': 'замечательное место, мне все очень понравилось, прекрасное обслуживание и вкусная еда, стильный интерьер, удобное расположение'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Чистота и атмосфера в заведении',
   'Обслуживание персонала',
   'Качество еды',
   'Качество доставки'],
  'review_text': 'приятное помещение,заказали пиццу,оперативно выполнили заказ,в помещении чисто,персонал вежливый)) советую всем,кто любит комфортно провести время и вкусно покушать!'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Обслуживание персонала', 'Качество еды'],
  'review_text': 'Вежливые, доброжелательные сотрудники. Быстрое обслуживание, добавки в пиццу не жалеют.'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды',
   'Чистота и атмосфера в заведении',
   'Ассортимент'],
  'review_text': 'Вкусно здесь, готовят быстро, чисто в самом ресторане и в туалете. Есть второй этаж - всегда есть свободные места.  Уже стоит новогодняя ёлочка с фирменными шарами.'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды'],
  'review_text': 'Раньше сюда не заходила, и вот решилась. Я была очень удивлена тому, насколько вкусно здесь готовят! Пицца очень вкусная, паста карбонара - умопомрачительная! Наггетсы очень сочные. Всем рекомендую)'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Обслуживание персонала', 'Качество еды'],
  'review_text': 'Филиал на Полянке очень радует! Всегда милые и вежливые сотрудники! Пицца свежая и горячая! Спасибо за это!'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды', 'Чистота и атмосфера в заведении'],
  'review_text': 'Хорошее заведение. Чистота, спокойствие и тишина. Сделали заказ, получили и поели на втором этаже. Пицца вкусная. Спасибо. Есть туалеты на первом и втором этажах.'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Чистота и атмосфера в заведении', 'Качество еды'],
  'review_text': 'Отличное местоположение, славится своей красотой, от себя добавлю, что если сюда собрать компанию на любые праздники, в том числе на день рождения, то это будет супер. Я надеюсь, это заведение наберет популярность. И плюс, у них очень вкусная карбонара'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Обслуживание персонала',
   'Чистота и атмосфера в заведении',
   'Качество доставки'],
  'review_text': 'Обожаю эту пиццерию на Полянке, быстрое обслуживание, всегда есть, где сесть, чисто, очень нравится второй этаж, очень уютно. Рекомендую как на доставку, так и провести время в самом заведении.'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Обслуживание персонала', 'Качество еды', 'Качество доставки'],
  'review_text': 'Чисто. Вежливые ребята на кассе. Быстро приготовили мне пиццу, что важно, тк мало времени. Пицца хорошая, горячая. Спамто большое. Буду заходить с оказией'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Чистота и атмосфера в заведении', 'None'],
  'review_text': 'Из плюсов:  - близко от метро (несмотря на это народу умеренно) - удобная расстановка столов - очень хорошо обыгран 2…'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды',
   'Цены',
   'Обслуживание персонала',
   'Чистота и атмосфера в заведении'],
  'review_text': 'Очень вкусная паста карбонара, прям 10/10, особенно за такю цену. Персонал доброжелательный, внутри чисто и тихо, очень притяно здесь проводить время!'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Чистота и атмосфера в заведении',
   'Обслуживание персонала',
   'Качество еды'],
  'review_text': 'Отличное место, всегда уютно, тепло и вкусненько))) 😃 😙 🤩 😻 😈 🙂 😃 😙  Персонал очень приветливый и дружелюбный, всегда на высоте))) Приходите, мы вас ждём)…'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды',
   'Чистота и атмосфера в заведении',
   'Обслуживание персонала'],
  'review_text': 'Очень вкусно. Хорошая обстановка. Быстрое обслуживание.'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды', 'Обслуживание персонала'],
  'review_text': 'Додо понравилось с первого раза, пицца вкусная, быстрое обслуживание. Обаятельная Мира всегда улыбается. Каждый День захожу на кофе и пиццу'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды',
   'Цены',
   'Чистота и атмосфера в заведении',
   'Качество доставки'],
  'review_text': 'Места на втором этаже уютные. Пицца горячая, вкусная. Временем ожидания довольна. Предложили комбо для сокращения цены, хотя я специально этого не искала'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Чистота и атмосфера в заведении',
   'Ассортимент',
   'Цены',
   'Качество еды'],
  'review_text': 'Моя любимая Додо пицца! Чисто, красиво, всегда приятно зайти! Постоянно новинки и акции)  Обожаю бруслетики🍕 Кофе всегда по приятной цене🥥☕'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Обслуживание персонала',
   'Качество еды',
   'Цены',
   'Чистота и атмосфера в заведении'],
  'review_text': 'Очень комфортное и уютное место, сотрудники очень вежливые приятная атмосфера и музыка. Еда и цены понравились, обслуживание быстрое. Рекомендую к посещению'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды', 'Обслуживание персонала'],
  'review_text': 'Обожаю эту пиццерию , особенно комбо : два кусочка пиццы и любимый кофе с лесным орехом , персонал очень вежлив и заботлив .'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды', 'Цены', 'Чистота и атмосфера в заведении'],
  'review_text': 'Пиццерия очень хорошая. Расположена недалеко от метро. Цены приемлемые. Еда очень вкусная. В заведении приятная атмосфера. Места много-два этажа.'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды', 'Качество доставки', 'Цены'],
  'review_text': 'Минусы : не заметила Плюсы : вкусно +довольно быстро принесли , еда товарного вида Комментарии : люблю Додо , очень вкусно и не очень дорого'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды', 'Чистота и атмосфера в заведении'],
  'review_text': 'Добрый вечер! Часто захожу в пиццерии Додо. Всегда вкусно, чисто. Атмосфера приятная.  Сегодня на Б. Полянка заказали додстер - вкусно и сытно😊 И кофе здесь отличный!'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды', 'Цены', 'Чистота и атмосфера в заведении'],
  'review_text': 'Паста с креветками очень вкусная! По демократичной цене не ожидали такого качества, всем рекомендую!  В самом заведении чисто и приятно находиться, людей немного'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды',
   'Обслуживание персонала',
   'Чистота и атмосфера в заведении'],
  'review_text': 'хорошее и уютное место, хорошее обслуживание и очень вкусная пицца, никогда не подводит, часто сюда хожу, всем советую!!'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Чистота и атмосфера в заведении',
   'Качество еды',
   'Качество доставки'],
  'review_text': 'Чудное место! Просидели 5 часов, очень комфортно, приятная музыка. Вкусно, быстро. Нам всё понравилось! Кофе яблочный пирог отдельный кайф💚💅'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Чистота и атмосфера в заведении', 'Качество еды'],
  'review_text': 'Очень удобно и комфортно всегда зайти, сесть с ноутбуком, поесть и поработать. Всегда чисто, есть розетки и вкусная качественная пицца!'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды',
   'Чистота и атмосфера в заведении',
   'Обслуживание персонала'],
  'review_text': 'Спасибо за очень вкусную еду, уют, свободные места и чистоту! Девушка на кассе милашка. Приятно, когда так обслуживают. В шумной Москве милый уголок уюта)'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды', 'Ассортимент'],
  'review_text': 'Очень приятное место, блюда вкусные и большой выбор. Идеально с утра, разнообразные закуски и возможность заказать завтрак с собой. Есть даже паста'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды',
   'Цены',
   'Обслуживание персонала',
   'Чистота и атмосфера в заведении'],
  'review_text': 'Хорошее бюджетное место. Очень уютно и комфортно. Обслуживание на высоте. Есть несколько зон приёма пищи. Пицца вкусная, недорогая. Спасибо!'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Обслуживание персонала',
   'Качество еды',
   'Чистота и атмосфера в заведении'],
  'review_text': 'Частенько захожу сюда после работы. Кафе чистое, персонал вежливый, готовят быстро и вкусно. Однозначно рекомендую данное заведение'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды',
   'Чистота и атмосфера в заведении',
   'Качество доставки'],
  'review_text': 'Часто сидим с друзьями, очень уютно и весело каждый раз. Готовят быстро, даже в час пик,пицца и додстеры вкусные'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды', 'Чистота и атмосфера в заведении'],
  'review_text': 'Хорошая пиццерия, чистая и просторная. Очень нравится пицца. Расположение додо хорошее, удобно забегать утром за кофе. Всем рекомендую и советую!'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды',
   'Чистота и атмосфера в заведении',
   'Обслуживание персонала'],
  'review_text': 'Часто сюда приходим, очень нравится паста в меню, у вас всегда чисто и уютно, отдельная благодарность Дарье, очень милая и улыбчивая девушка. Спасибо!'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды',
   'Обслуживание персонала',
   'Чистота и атмосфера в заведении'],
  'review_text': 'Замечательное место, пицца очень вкусная, персонал невероятно вежливый и милый! В помещении чисто и приятно.'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды',
   'Обслуживание персонала',
   'Чистота и атмосфера в заведении'],
  'review_text': 'Были сегодня в Додо пицца. Очень уютно, пицца вкусная, быстро приготовили . Отличный коллектив, встретили с улыбкой. Все супер.'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды',
   'Чистота и атмосфера в заведении',
   'Ассортимент'],
  'review_text': 'Любим эту пиццу. Удобное расположение в центре. Быстро, вкусно. Детям в ожидании можно порисовать 👍.Рекомендуем.'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды',
   'Обслуживание персонала',
   'Чистота и атмосфера в заведении'],
  'review_text': 'Это чудесное место, где можно насладиться вкусной едой и приятной атмосферой. Персонал здесь очень вежливый, а повара работают быстро и качественно. Спасибо вам!👍👍👍👍'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды',
   'Обслуживание персонала',
   'Чистота и атмосфера в заведении'],
  'review_text': 'Прекрасное место, кассир тоже хорошо справляется, всегда хочется возвращаться, все теплое и вкусное, крайне рекомендую это место к посещению'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды', 'Чистота и атмосфера в заведении'],
  'review_text': 'Очень вкусные додстеры, всегда тут обедаю. На втором этаже почти всегда есть свободные столы, готовят быстро'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды',
   'Обслуживание персонала',
   'Чистота и атмосфера в заведении'],
  'review_text': 'Прекрасное место, очень вкусно. Сотрудники доброжелательные и позитивные. Порадовало быстрое приготовление блюд и интерьер.'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды'],
  'review_text': 'очень вкусная пицца!! заказывала Баварскую, хоть и порезана странно и ингредиенты хаотично раскиданы, но из-за этого она не стала менее вкусной. Я наелась и это самое главное  люблю Додо 😁🥰🤍'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Чистота и атмосфера в заведении', 'Обслуживание персонала'],
  'review_text': 'Любимое место! Совсем недалеко от метро, удобно встречаться с друзьями. На втором этаже есть уютные столики, где можно провести время за разговорами ) Не знаю как другим, мне персонал попадался всегда приветливый. Там…'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Качество еды',
   'Чистота и атмосфера в заведении',
   'Обслуживание персонала'],
  'review_text': 'Уютное, красивое и главное вкусное заведение, приятная атмосфера, дружелюбный и приветливый персонал, рекомендую к посещению!'},
 {'company': 'Додо:',
  'sentiment': 'positive',
  'reason_n': 'None',
  'reason_p': ['Обслуживание персонала', 'Качество доставки'],

In [94]:
pd.DataFrame(result).to_csv('part_of_reviews.csv')

In [95]:
pd.DataFrame(result)

,company,sentiment,reason_n,reason_p,review_text
0,Додо:,positive,None,[Чистота и атмосфера в заведении],"Недавно посетил пиццерию ""До До"" и остался в п..."
1,Додо:,positive,None,[Качество еды],"Зашли с мамой в пиццерию «До-до», заказали нов..."
2,Додо:,positive,None,"[Чистота и атмосфера в заведении, Ассортимент]","Приятная пиццерия, дизайн логотипа на кафешке ..."
3,Додо:,positive,None,"[Чистота и атмосфера в заведении, Обслуживание...",Очень нравится приходить именно сюда! Здесь на...
4,Додо:,positive,None,"[Обслуживание персонала, Качество еды, Цены]",Додо пиццу очень люблю и оказавшись в Москве н...
...,...,...,...,...,...
987,Zotman:,positive,None,[Качество еды],Суперские пиццы. Еда всегда на высоте.
988,Zotman:,positive,None,[Качество еды],Всё супер всё нравится Вкусная пицца и кофе ✴...
989,Zotman:,positive,None,"[Качество еды, Обслуживание персонала]","Вкусная пицца, неплохая кулинария. Вежливый пе..."
990,Zotman:,positive,None,Качество еды,Любимая пицца)
991,Zotman:,positive,None,"[Качество еды, Качество доставки]",Шикарная пицца для заказа на дом.

In [71]:
len(result)

942

In [85]:
df = df[df.company != 'Папа']
df['i'] = [i % 4 == 0 for i in range(len(df))]

In [86]:
df = df[df['i']]

In [88]:
len(df)

992

In [65]:
sum(df2.text.apply(lambda s: s in df.text))

0

In [56]:
df.to_csv('reviews_all.csv')